### ISSUE TITLE
How to make new line 

### ISSUE THREAD

**Issue by reactmore** [magicjar/whatsapp-widget#1]
hi where the script output to edit this

Name: ad;Email: asd@AD.COM;Subject: asd;Message: asd;

to 

Name: ad

Email: asd@AD.COM

Subject: asd

Message: asd;

**Comment by reactmore** [comment]
hey can give me example toggleable custom from ?

<button class="button" data-toggle="wa-chat" class="wa-widget-content"
        data-target="#billing-support">Show Widget</button>

uncaught TypeError: Cannot read property 'classList' of null
    at Chat._show (whatsapp-widget.js:226)
    at Chat.toggle (whatsapp-widget.js:154)
    at HTMLButtonElement.<anonymous> (whatsapp-widget.js:203)
_show @ whatsapp-widget.js:226
toggle @ whatsapp-widget.js:154
(anonymous) @ whatsapp-widget.js:203

**Comment by magicjar** [comment]
I have fixed the new line bug. Please redownload it.
As for toggleable custom form. I have updated the README and added an example in index.html.

**Comment by reactmore** [comment]
Thanks for help @magicjar , 

why you set readonly on android sir ? Why not to use api.whatsapp.com if its android / mobile or in the future there will be problems if use api.whatsApp

**Comment by magicjar** [comment]
Fixed.
It was a stupid mistake, I am ashamed of myself. :laughing:
